### ISSUE TITLE
bikeshed: can we rename the organization?

### ISSUE THREAD

**Issue by dtardon** [redhat-plumbers/lets-test-migration#3]
Capital letters in combination with dashes feel redundant. Suggested names:
- red-hat-plumbers
- redhat-plumbers
- rhplumbers

The visible name can still be set to "Red Hat - Plumbers"--or whatever else--in profile.

**Comment by lnykryn** [comment]
I would vote for redhat-plumbers

**Comment by jamacku** [comment]
Good point, done.
